// <auto-generated />
namespace Cepheus.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ConvertImagePathToByteArray : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConvertImagePathToByteArray));
        
        string IMigrationMetadata.Id
        {
            get { return "201303291515317_ConvertImagePathToByteArray"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
