// <auto-generated />
namespace Cepheus.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Check : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Check));
        
        string IMigrationMetadata.Id
        {
            get { return "201304010426423_Check"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
